Repository SOPT-all/35-APPJAM-SERVER-DASH, pull requests merged in 2025-01, with the labels that each got.

#5 feat: 초기 데이터베이스 엔티티 구현
  build.gradle
  src/main/java/be/dash/dashserver/DashServerApplication.java
  src/main/java/be/dash/dashserver/core/domain/common/Genre.java
  src/main/java/be/dash/dashserver/core/domain/common/Level.java
  src/main/java/be/dash/dashserver/core/domain/member/Role.java
  src/main/java/be/dash/dashserver/core/domain/member/SocialProvider.java
  src/main/java/be/dash/dashserver/database/core/common/BaseCreatedAtEntity.java
  src/main/java/be/dash/dashserver/database/core/common/BaseTimeEntity.java
  src/main/java/be/dash/dashserver/database/core/config/JpaAuditingConfig.java
  src/main/java/be/dash/dashserver/database/core/favorite/FavoriteJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/favorite/FavoriteJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/genre/GenreJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/genre/GenreJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonImageJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntityRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRoundJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRoundJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonVideoJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonVideoJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/member/MemberJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/member/MemberJpaRepositoy.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/student/StudentGenreJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/student/StudentGenreJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/student/StudentJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/student/StudentJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherImageJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherImageJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherVideoJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherVideoJpaRepository.java
  src/test/java/be/dash/dashserver/ServerApplicationTests.java
Labels: enhancement

#8 feat: ci workflow
  .github/workflows/ci.yml
  build.gradle
Labels: feat

#10 feat: jwt 로직 구현
  build.gradle
  src/main/java/be/dash/dashserver/core/auth/JwtProperties.java
  src/main/java/be/dash/dashserver/core/auth/JwtPropertiesConfiguration.java
  src/main/java/be/dash/dashserver/core/auth/JwtTokenProvider.java
  src/main/java/be/dash/dashserver/core/auth/JwtTokenValidator.java
  src/main/java/be/dash/dashserver/core/auth/KeyGenerator.java
  src/main/java/be/dash/dashserver/core/auth/UnAuthorizedException.java
  src/test/java/be/dash/dashserver/core/auth/JwtTokenProviderTest.java
  src/test/java/be/dash/dashserver/core/auth/JwtTokenValidatorTest.java
Labels: feat

#15 feat: 이미지 업로드 기능을 구현합니다
  build.gradle
  src/main/java/be/dash/dashserver/api/core/image/ImageController.java
  src/main/java/be/dash/dashserver/api/core/image/dto/ImagePostResponse.java
  src/main/java/be/dash/dashserver/api/support/GlobalExceptionHandler.java
  src/main/java/be/dash/dashserver/core/exception/BadGatewayException.java
  src/main/java/be/dash/dashserver/core/exception/BadRequestException.java
  src/main/java/be/dash/dashserver/core/image/ImageService.java
  src/main/java/be/dash/dashserver/core/image/ImageUploader.java
  src/main/java/be/dash/dashserver/external/config/S3Config.java
  src/main/java/be/dash/dashserver/external/config/S3Properties.java
  src/main/java/be/dash/dashserver/external/s3/S3ImageUploader.java
  src/main/resources/application-local.yml
  src/test/resources/application-test.yml
Labels: api

#18 feat: 외부 검색 기능 구현
  src/main/java/be/dash/dashserver/api/core/auth/AuthController.java
  src/main/java/be/dash/dashserver/api/core/auth/dto/LoginResponse.java
  src/main/java/be/dash/dashserver/api/core/external/ImageController.java
  src/main/java/be/dash/dashserver/api/core/external/LocationSearchController.java
  src/main/java/be/dash/dashserver/api/core/external/dto/ImagePostResponse.java
  src/main/java/be/dash/dashserver/api/core/external/dto/LocationResponse.java
  src/main/java/be/dash/dashserver/api/core/external/dto/LocationsResponse.java
  src/main/java/be/dash/dashserver/api/support/GlobalExceptionHandler.java
  src/main/java/be/dash/dashserver/core/auth/LoginService.java
  src/main/java/be/dash/dashserver/core/auth/RefreshToken.java
  src/main/java/be/dash/dashserver/core/auth/TokenParser.java
  src/main/java/be/dash/dashserver/core/auth/dto/LoginResult.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Location.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Locations.java
  src/main/java/be/dash/dashserver/core/external/LocationSearchClientApi.java
  src/main/java/be/dash/dashserver/core/external/LocationSearchService.java
  src/main/java/be/dash/dashserver/external/config/naver/NaverConfig.java
  src/main/java/be/dash/dashserver/external/config/naver/NaverProperties.java
  src/main/java/be/dash/dashserver/external/config/s3/S3Config.java
  src/main/java/be/dash/dashserver/external/config/s3/S3Properties.java
  src/main/java/be/dash/dashserver/external/naver/NaverClientCaller.java
  src/main/java/be/dash/dashserver/external/s3/S3ImageUploader.java
  src/main/resources/application-local.yml
  src/test/java/be/dash/dashserver/api/core/auth/AuthControllerTest.java
  src/test/java/be/dash/dashserver/api/core/external/LocationSearchControllerTest.java
  src/test/java/be/dash/dashserver/core/auth/JwtTokenGeneratorTest.java
  src/test/java/be/dash/dashserver/core/auth/LoginServiceTest.java
  src/test/java/be/dash/dashserver/core/auth/TokenParserTest.java
  src/test/resources/application-test.yml
Labels: api

#17 feat: Dancer 검색 구현 #13
  src/main/java/be/dash/dashserver/api/core/lesson/LessonController.java
  src/main/java/be/dash/dashserver/api/core/teacher/TeacherController.java
  src/main/java/be/dash/dashserver/api/core/teacher/dto/TeacherResponse.java
  src/main/java/be/dash/dashserver/api/core/teacher/dto/TeacherResponses.java
  src/main/java/be/dash/dashserver/api/support/converter/SortOptionConverter.java
  src/main/java/be/dash/dashserver/core/domain/lesson/LessonSortOption.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Lessons.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonRepository.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonService.java
  src/main/java/be/dash/dashserver/core/domain/teacher/Teacher.java
  src/main/java/be/dash/dashserver/core/domain/teacher/TeacherLessonGenres.java
  src/main/java/be/dash/dashserver/core/domain/teacher/Teachers.java
  src/main/java/be/dash/dashserver/core/domain/teacher/projection/TeacherLessonCount.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherRepository.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherService.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntityRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/member/MemberJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherImageJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherRepositoryAdapter.java
  src/test/java/be/dash/dashserver/api/core/lesson/LessonControllerTest.java
  src/test/java/be/dash/dashserver/api/core/teacher/TeacherControllerTest.java
  src/test/java/be/dash/dashserver/api/support/converter/LessonSortOptionConverterTest.java
  src/test/java/be/dash/dashserver/core/domain/lesson/LessonSortOptionTest.java
  src/test/java/be/dash/dashserver/core/domain/lesson/service/LessonServiceTest.java
  src/test/java/be/dash/dashserver/core/domain/teacher/service/TeacherServiceTest.java
  src/test/java/be/dash/dashserver/core/fixture/LessonFixture.java
  src/test/java/be/dash/dashserver/core/fixture/MemberFixture.java
  src/test/java/be/dash/dashserver/core/fixture/TeacherFixture.java
  src/test/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapterTest.java
  src/test/java/be/dash/dashserver/database/core/teacher/TeacherRepositoryAdapterTest.java
  src/test/java/be/dash/dashserver/database/fixture/MemberJpaEntityFixture.java
  src/test/java/be/dash/dashserver/database/fixture/TeacherJpaEntityFixture.java
Labels: api

#20 feat: lesson 도메인 분리
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonResponse.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Lesson.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Location.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntity.java
Labels: enhancement

#32 feat: 수업 등록 api
  src/main/java/be/dash/dashserver/api/core/auth/AuthController.java
  src/main/java/be/dash/dashserver/api/core/lesson/LessonController.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/RoundRequest.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/createLessonRequest.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Lesson.java
  src/main/java/be/dash/dashserver/core/domain/lesson/LessonImages.java
  src/main/java/be/dash/dashserver/core/domain/lesson/LessonSortOption.java
  src/main/java/be/dash/dashserver/core/domain/lesson/LessonVideos.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Location.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Round.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Rounds.java
  src/main/java/be/dash/dashserver/core/domain/lesson/command/CreateLessonCommand.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonRepository.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonService.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonImageJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonImageJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRoundJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonVideoJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherRepositoryAdapter.java
  src/test/java/be/dash/dashserver/api/core/lesson/LessonControllerTest.java
  src/test/java/be/dash/dashserver/core/fixture/LessonFixture.java
  src/test/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapterTest.java
Labels: api

#35 feat: 댄서(선생님) 프로필 조회 #33
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonResponse.java
  src/main/java/be/dash/dashserver/api/core/teacher/TeacherController.java
  src/main/java/be/dash/dashserver/api/core/teacher/dto/LessonSummary.java
  src/main/java/be/dash/dashserver/api/core/teacher/dto/TeacherDetailResponse.java
  src/main/java/be/dash/dashserver/api/core/teacher/dto/TeacherResponse.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Images.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Lesson.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Videos.java
  src/main/java/be/dash/dashserver/core/domain/lesson/command/CreateLessonCommand.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonRepository.java
  src/main/java/be/dash/dashserver/core/domain/teacher/Teacher.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherRepository.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherService.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/dto/TeacherDetailResult.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntityRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/member/MemberRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/student/StudentGenreJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/student/StudentGenreJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/student/StudentJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/student/StudentJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherImageRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherVideoJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherVideoJpaRepository.java
  src/test/java/be/dash/dashserver/api/core/teacher/TeacherControllerTest.java
  src/test/java/be/dash/dashserver/core/fixture/LessonFixture.java
Labels: api

#40 feat: 수업 정보 상세 조회
  src/main/java/be/dash/dashserver/api/core/lesson/LessonController.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/CreateLessonRequest.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonDetailResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonLevelResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonRoundResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonRoundResponses.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonStatus.java
  src/main/java/be/dash/dashserver/api/core/teacher/TeacherController.java
  src/main/java/be/dash/dashserver/api/core/teacher/dto/TeacherResponse.java
  src/main/java/be/dash/dashserver/core/domain/common/Keyword.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonRepository.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonService.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationRepository.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationService.java
  src/main/java/be/dash/dashserver/core/domain/teacher/Teacher.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherRepository.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherService.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntityRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRoundJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonSpecifications.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonVideoJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherImageJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherVideoJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/projection/TeacherLessonCount.java
  src/test/java/be/dash/dashserver/api/core/lesson/LessonControllerTest.java
  src/test/java/be/dash/dashserver/api/core/teacher/TeacherControllerTest.java
  src/test/java/be/dash/dashserver/core/domain/lesson/service/LessonServiceTest.java
  src/test/java/be/dash/dashserver/core/domain/teacher/service/TeacherServiceTest.java
  src/test/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapterTest.java
  src/test/java/be/dash/dashserver/database/core/teacher/TeacherRepositoryAdapterTest.java
Labels: api

#42 feat: 수업 예약 페이지 조회 #41
  src/main/java/be/dash/dashserver/api/core/lesson/LessonController.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonDetailResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonLevelResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonReservationResponse.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonResponse.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonService.java
  src/main/java/be/dash/dashserver/core/domain/member/service/MemberService.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapter.java
  src/test/java/be/dash/dashserver/api/core/lesson/LessonControllerTest.java
Labels: api

#44 feat: 수업 예약 #43
  src/main/java/be/dash/dashserver/api/config/WebMvcConfig.java
  src/main/java/be/dash/dashserver/api/core/reservation/ReservationController.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationRepository.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationService.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationRepositoryAdapter.java
Labels: api

#45 feat: 마이페이지 조회 api
  src/main/java/be/dash/dashserver/api/core/external/ImageController.java
  src/main/java/be/dash/dashserver/api/core/lesson/LessonController.java
  src/main/java/be/dash/dashserver/api/core/member/MemberController.java
  src/main/java/be/dash/dashserver/api/core/member/MemberFacade.java
  src/main/java/be/dash/dashserver/api/core/member/dto/MemberResponse.java
  src/main/java/be/dash/dashserver/api/core/member/dto/ReservationDetailedResponse.java
  src/main/java/be/dash/dashserver/api/core/member/dto/ReservationResponse.java
  src/main/java/be/dash/dashserver/api/core/member/dto/ReservationsResponse.java
  src/main/java/be/dash/dashserver/api/core/member/dto/RoundResponse.java
  src/main/java/be/dash/dashserver/api/core/reservation/ReservationController.java
  src/main/java/be/dash/dashserver/api/support/PermissionInterceptor.java
  src/main/java/be/dash/dashserver/core/domain/common/AttendStatus.java
  src/main/java/be/dash/dashserver/core/domain/lesson/Lesson.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonRepository.java
  src/main/java/be/dash/dashserver/core/domain/member/service/MemberInformationResult.java
  src/main/java/be/dash/dashserver/core/domain/member/service/MemberRepository.java
  src/main/java/be/dash/dashserver/core/domain/member/service/MemberService.java
  src/main/java/be/dash/dashserver/core/domain/member/service/ReservationResult.java
  src/main/java/be/dash/dashserver/core/domain/reservation/Reservation.java
  src/main/java/be/dash/dashserver/core/domain/reservation/Reservations.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationRepository.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationService.java
  src/main/java/be/dash/dashserver/core/domain/teacher/Teacher.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherService.java
  src/main/java/be/dash/dashserver/database/core/common/BaseCreatedAtEntity.java
  src/main/java/be/dash/dashserver/database/core/favorite/FavoriteJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntityRepository.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRoundJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/member/MemberJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/member/MemberRepositoryAdapter.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationRepositoryAdapter.java
  src/test/java/be/dash/dashserver/api/core/member/MemberControllerTest.java
Labels: api

#62 fix: 예약 상세 응답 변경
  src/main/java/be/dash/dashserver/api/core/member/dto/ReservationDetailedResponse.java
Labels: bug

#68 fix: 누락 응답 필드 추가
  src/main/java/be/dash/dashserver/api/core/lesson/LessonController.java
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonReservationResponse.java
  src/main/java/be/dash/dashserver/api/core/teacher/TeacherController.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonRepository.java
  src/main/java/be/dash/dashserver/core/domain/teacher/service/TeacherService.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonRepositoryAdapter.java
Labels: bug

#70 fix: 응답 필드 누락
  src/main/java/be/dash/dashserver/api/core/member/MemberController.java
  src/main/java/be/dash/dashserver/api/core/member/MemberFacade.java
  src/main/java/be/dash/dashserver/api/core/member/MyLessonDetailedResponse.java
  src/main/java/be/dash/dashserver/api/core/member/dto/ApplyStatus.java
  src/main/java/be/dash/dashserver/api/core/member/dto/MemberReservationResponse.java
  src/main/java/be/dash/dashserver/api/core/member/dto/MyLessonResponse.java
  src/main/java/be/dash/dashserver/core/domain/reservation/Reservations.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationService.java
Labels: bug

#72 fix: 엔티티 저장 식별값 변경
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationRepository.java
  src/main/java/be/dash/dashserver/core/domain/reservation/service/ReservationService.java
  src/main/java/be/dash/dashserver/database/core/reservation/ReservationRepositoryAdapter.java
Labels: bug

#74 fix: 쿼리 파라미터 변경
  src/main/java/be/dash/dashserver/api/core/member/MemberFacade.java
  src/main/java/be/dash/dashserver/core/domain/lesson/service/LessonService.java
  src/main/java/be/dash/dashserver/core/domain/member/service/MemberRepository.java
  src/main/java/be/dash/dashserver/core/domain/member/service/MemberService.java
  src/main/java/be/dash/dashserver/database/core/member/MemberRepositoryAdapter.java
Labels: bug

#78 fix: 응답 필드 값 수정
  src/main/java/be/dash/dashserver/api/core/lesson/dto/LessonResponse.java
Labels: bug

#82 refactor: 호환 가능 확장자 파일 추가 및 파일 최대 용량 제한
  src/main/java/be/dash/dashserver/api/support/GlobalExceptionHandler.java
  src/main/java/be/dash/dashserver/external/s3/S3ImageUploader.java
Labels: enhancement

#84 fix: Teacher 조회 시 Lesson이 없어도 조회 가능
  src/main/java/be/dash/dashserver/database/core/lesson/LessonJpaEntityRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherJpaRepository.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherRepositoryAdapter.java
Labels: bug

#86 fix: Permission 범위 수정
  src/main/java/be/dash/dashserver/api/core/lesson/LessonController.java
Labels: bug

#90 fix: image url 경로 최대 길이 수정
  src/main/java/be/dash/dashserver/database/core/advertisement/AdvertisementJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonImageJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/lesson/LessonVideoJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/student/StudentJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherImageJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherJpaEntity.java
  src/main/java/be/dash/dashserver/database/core/teacher/TeacherVideoJpaEntity.java
Labels: bug
